import type { Deal } from "@/lib/itinerary/types";

const futureExpiry = "2026-12-31T15:59:59.000Z";

export const mockDeals: Deal[] = [
  {
    id: "ramen-stamp",
    title: "Hidden Ramen Stamp Trail",
    description:
      "Three compact ramen counters between Orchard and Dhoby Ghaut with a free gyoza reward on the final stop.",
    category: "Food",
    source: "mock",
    source_url: "https://www.visitsingapore.com/see-do-singapore/places-to-see/orchard/",
    price: 18,
    discount_amount: 6,
    location: "Orchard to Dhoby Ghaut",
    lat: 1.3006,
    lng: 103.8397,
    expiry_at: futureExpiry,
    tags: ["food", "walkable", "discount", "date-night"],
    best_time: "6:15 PM",
  },
  {
    id: "arcade-hour",
    title: "Retro Arcade Hour",
    description:
      "Unlimited tokens for a one-hour window, with rhythm games and old fighting cabinets near Somerset.",
    category: "Activity",
    source: "mock",
    source_url: "https://www.visitsingapore.com/see-do-singapore/places-to-see/orchard/",
    price: 14,
    discount_amount: 4,
    location: "Somerset",
    lat: 1.3003,
    lng: 103.8377,
    expiry_at: futureExpiry,
    tags: ["games", "indoor", "budget", "playful"],
    best_time: "8:00 PM",
  },
  {
    id: "mystery-dessert",
    title: "Mystery Dessert Counter",
    description:
      "A rotating plated dessert menu where the counter picks a flavor profile based on your mood.",
    category: "Food",
    source: "mock",
    source_url: "https://www.visitsingapore.com/dining-drinks-singapore/",
    price: 12,
    discount_amount: 3,
    location: "Haji Lane",
    lat: 1.3009,
    lng: 103.8593,
    expiry_at: futureExpiry,
    tags: ["dessert", "cafe", "deal", "spontaneous"],
    best_time: "9:15 PM",
  },
  {
    id: "gallery-afterhours",
    title: "Gallery Afterhours",
    description:
      "Late gallery entry, mini curator talks, and a quiet courtyard bar with mocktails under S$10.",
    category: "Lifestyle",
    source: "mock",
    source_url: "https://www.nationalgallery.sg/",
    price: 10,
    discount_amount: null,
    location: "Civic District",
    lat: 1.2905,
    lng: 103.8515,
    expiry_at: futureExpiry,
    tags: ["museum", "night", "artsy", "conversation"],
    best_time: "7:00 PM",
  },
  {
    id: "rooftop-cinema",
    title: "Rooftop Cinema Picnic",
    description:
      "Outdoor movie night with beanbags, skyline views, and snack bundles cheaper than a full dinner plan.",
    category: "Activity",
    source: "mock",
    source_url: "https://www.visitsingapore.com/festivals-events-singapore/",
    price: 18,
    discount_amount: 5,
    location: "Bugis Rooftop",
    lat: 1.2992,
    lng: 103.8556,
    expiry_at: futureExpiry,
    tags: ["movie", "outdoor", "promo", "date-night"],
    best_time: "7:45 PM",
  },
  {
    id: "coffee-walk",
    title: "Two-Stop Coffee Walk",
    description:
      "A low-pressure coffee and pastry route with enough walking time to make the evening feel planned.",
    category: "Food",
    source: "mock",
    source_url: "https://www.visitsingapore.com/dining-drinks-singapore/",
    price: 16,
    discount_amount: 2,
    location: "Orchard Road",
    lat: 1.3048,
    lng: 103.8318,
    expiry_at: futureExpiry,
    tags: ["coffee", "walk", "casual", "date-night"],
    best_time: "5:30 PM",
  },
  {
    id: "indie-market",
    title: "Indie Makers Market",
    description:
      "Local candles, zines, ceramics, thrift racks, and a coffee cart tucked into the back lane.",
    category: "Lifestyle",
    source: "mock",
    source_url: "https://www.visitsingapore.com/see-do-singapore/neighbourhoods/joo-chiat-katong/",
    price: 8,
    discount_amount: null,
    location: "Joo Chiat",
    lat: 1.3148,
    lng: 103.9003,
    expiry_at: futureExpiry,
    tags: ["market", "shopping", "browse", "budget"],
    best_time: "4:30 PM",
  },
  {
    id: "midnight-pottery",
    title: "Midnight Pottery Jam",
    description:
      "Clay, playlists, and a tiny dessert bar after dark. Good for dates that need less talking and more making.",
    category: "Activity",
    source: "mock",
    source_url: "https://www.visitsingapore.com/see-do-singapore/",
    price: 28,
    discount_amount: 10,
    location: "Tiong Bahru Studio",
    lat: 1.2846,
    lng: 103.8326,
    expiry_at: futureExpiry,
    tags: ["workshop", "indoor", "cozy", "date-night"],
    best_time: "8:30 PM",
  },
];
